---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTable
metadata:
  name: dev-private
spec:
  forProvider:
    region: us-west-2
    tags:
      Name: dev-private
    vpcIdRef:
      name: dev-main
---
apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: Route
metadata:
  name: dev-private-route
spec:
  forProvider:
    region: us-west-2
    destinationCIDRBlock: 0.0.0.0/0
    natGatewayIdRef:
      name: dev-nat
    routeTableIdRef:
      name: dev-private
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  name: dev-private-us-west-2a
spec:
  forProvider:
    region: us-west-2
    routeTableIdRef:
      name: dev-private
    subnetIdRef:
      name: dev-private-us-west-2a
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  name: dev-private-us-west-2b
spec:
  forProvider:
    region: us-west-2
    routeTableIdRef:
      name: dev-private
    subnetIdRef:
      name: dev-private-us-west-2b
