---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTable
metadata:
  name: dev-public
spec:
  forProvider:
    region: us-west-2
    tags:
      Name: dev-public
    vpcIdRef:
      name: dev-main
  providerConfigRef:
    name: aws-provider
---
apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: Route
metadata:
  name: dev-public-route
spec:
  forProvider:
    region: us-west-2
    destinationCIDRBlock: 0.0.0.0/0
    natGatewayIdRef:
      name: dev-igw
    routeTableIdRef:
      name: dev-public
  providerConfigRef:
    name: aws-provider
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  name: dev-public-us-west-2a
spec:
  forProvider:
    region: us-west-2
    routeTableIdRef:
      name: dev-public
    subnetIdRef:
      name: dev-public-us-west-2a
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  name: dev-public-us-west-2b
spec:
  forProvider:
    region: us-west-2
    routeTableIdRef:
      name: dev-public
    subnetIdRef:
      name: dev-public-us-west-2b
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  name: dev-public-us-west-2c
spec:
  forProvider:
    region: us-west-2
    routeTableIdRef:
      name: dev-public
    subnetIdRef:
      name: dev-public-us-west-2c
---