apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: example-grafana
  namespace: grafana-operator
spec:
  config:
    log:
      mode: "console"
      level: "warn"
    auth:
      disable_signout_menu: true
    security:
      admin_user: "admin"
      admin_password: "admin"

